package com.lanou3g.the_project_a.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lanou3g.the_project_a.greendao.CollectionPerson;

import com.lanou3g.the_project_a.greendao.CollectionPersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionPersonDaoConfig;

    private final CollectionPersonDao collectionPersonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionPersonDaoConfig = daoConfigMap.get(CollectionPersonDao.class).clone();
        collectionPersonDaoConfig.initIdentityScope(type);

        collectionPersonDao = new CollectionPersonDao(collectionPersonDaoConfig, this);

        registerDao(CollectionPerson.class, collectionPersonDao);
    }
    
    public void clear() {
        collectionPersonDaoConfig.clearIdentityScope();
    }

    public CollectionPersonDao getCollectionPersonDao() {
        return collectionPersonDao;
    }

}
